import { formatMoney } from './currencies.mjs';
import {canonicalSubject,taxonomy} from './taxonomy.mjs';
import { extraCopy } from './review-translations.mjs';
import { sharedCopy } from './locale.mjs';
export const reviewCopy = {
  en: { title:'Staff review', intro:'Review the submitted profile and each proposed subject. Decisions do not publish a profile or verify credentials.', setup:'Staff review is awaiting activation.', signin:'Sign in on the instructor page, then return here.', denied:'This account does not have staff review access.', apply:'Instructor profile', refresh:'Refresh queue', out:'Sign out', empty:'No submitted applications.', revision:'Revision', profile:'Profile decision', subject:'Subject decision', feedback:'Feedback for the instructor', hint:'Explain any requested changes or rejection. This feedback is visible to the instructor.', save:'Save review', pending:'Pending', approved:'Approved', needs_changes:'Changes requested', rejected:'Rejected', excluded:'Private QA application — approval blocked', self:'You cannot review your own application.', saved:'Review saved. The application remains private.', error:'Could not load or save the review. Try refreshing.', stale:'The instructor changed this application. Refresh before reviewing.', required:'Add feedback explaining the changes or rejection.', submitted:'Submitted', status:'Application status', current:'Current review', awaiting:'Awaiting staff review', obsolete:'Editing your application requires a new review.', review:'Staff feedback', private:'Approval does not publish your profile.', loading:'Loading…' },
  fr: { title:'Examen par l’équipe', intro:'Examinez le profil envoyé et chaque matière proposée. Les décisions ne publient pas de profil et ne vérifient pas les diplômes.', setup:'L’examen par l’équipe est en attente d’activation.', signin:'Connectez-vous sur la page du profil enseignant, puis revenez ici.', denied:'Ce compte n’a pas accès à l’examen par l’équipe.', apply:'Profil enseignant', refresh:'Actualiser la liste', out:'Se déconnecter', empty:'Aucune candidature envoyée.', revision:'Version', profile:'Décision sur le profil', subject:'Décision sur la matière', feedback:'Commentaires pour l’enseignant', hint:'Expliquez les modifications demandées ou le refus. Ces commentaires sont visibles par l’enseignant.', save:'Enregistrer l’examen', pending:'En attente', approved:'Approuvé', needs_changes:'Modifications demandées', rejected:'Refusé', excluded:'Candidature de test privée — approbation bloquée', self:'Vous ne pouvez pas examiner votre propre candidature.', saved:'Examen enregistré. La candidature reste privée.', error:'Impossible de charger ou d’enregistrer l’examen. Essayez d’actualiser.', stale:'L’enseignant a modifié cette candidature. Actualisez avant de l’examiner.', required:'Ajoutez des commentaires expliquant les modifications ou le refus.', submitted:'Envoyé', status:'État de la candidature', current:'Examen actuel', awaiting:'En attente d’examen par l’équipe', obsolete:'La modification de votre candidature nécessite un nouvel examen.', review:'Commentaires de l’équipe', private:'L’approbation ne publie pas votre profil.', loading:'Chargement…' }
};
Object.assign(reviewCopy, extraCopy);
export const escapeReview = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escapeReview;
const subjectLabel=(s,locale)=>{const subject=canonicalSubject(s.category,s.subject);return subject?`${taxonomy.categories.find(c=>c.id===subject.categoryId).name[locale]} / ${subject.name[locale]}`:`${s.category} / ${s.subject}`;};
const array = value => Array.isArray(value) ? value : [];
export const fieldLabels = {
 en: {displayName:'Display name',headline:'Headline',bio:'Introduction',countryOfResidence:'Country of residence',city:'City',timezone:'Time zone',yearsExperience:'Years of experience',education:'Education',nativeLanguages:'Native languages',spokenLanguages:'Other languages',introductionVideo:'Introduction video URL',photoURL:'Photo URL',availabilityNotes:'Availability notes'},
 fr: {displayName:'Nom affiché',headline:'Titre',bio:'Présentation',countryOfResidence:'Pays de résidence',city:'Ville',timezone:'Fuseau horaire',yearsExperience:'Années d’expérience',education:'Formation',nativeLanguages:'Langues maternelles',spokenLanguages:'Autres langues',introductionVideo:'Lien de la vidéo de présentation',photoURL:'Lien de la photo',availabilityNotes:'Disponibilités'}
};
Object.assign(fieldLabels, {"ar": {"displayName": "الاسم المعروض", "headline": "العنوان", "bio": "التعريف", "countryOfResidence": "بلد الإقامة", "city": "المدينة", "timezone": "المنطقة الزمنية", "yearsExperience": "سنوات الخبرة", "education": "التعليم", "nativeLanguages": "اللغات الأم", "spokenLanguages": "لغات أخرى", "introductionVideo": "رابط فيديو التعريف", "photoURL": "رابط الصورة", "availabilityNotes": "ملاحظات المواعيد"}, "es": {"displayName": "Nombre público", "headline": "Titular", "bio": "Presentación", "countryOfResidence": "País de residencia", "city": "Ciudad", "timezone": "Zona horaria", "yearsExperience": "Años de experiencia", "education": "Formación", "nativeLanguages": "Lenguas maternas", "spokenLanguages": "Otros idiomas", "introductionVideo": "URL del video de presentación", "photoURL": "URL de la foto", "availabilityNotes": "Notas de disponibilidad"}});
function price(offering, locale) {
 try {
  return formatMoney(offering.priceMinor,offering.currency,locale);
 } catch { return `${offering.priceMinor} ${offering.currency}`; }
}

export function feedbackHTML(review, locale = 'en') {
  if (!review) return '';
  const t = reviewCopy[locale];
  return `<section class="notice" aria-label="${t.review}"><h2>${t.review}</h2><p>${t.profile}: ${e(t[review.profile_decision] || review.profile_decision)}</p><ul>${array(review.subject_decisions).map(s => `<li>${e(subjectLabel(s,locale))}: ${e(t[s.decision] || s.decision)}</li>`).join('')}</ul><p style="white-space:pre-wrap">${e(review.feedback)}</p><p>${t.private}</p></section>`;
}
export function applicationHTML(row, locale, viewerId) {
  const t = reviewCopy[locale];
  const own = row.user_id === viewerId;
  const blocked = own || row.excluded;
  const select = (name, value) => `<select name="${name}" ${own ? 'disabled' : ''}>${['pending','approved','needs_changes','rejected'].map(v => `<option value="${v}" ${value === v ? 'selected' : ''} ${v === 'approved' && blocked ? 'disabled' : ''}>${t[v]}</option>`).join('')}</select>`;
  const p = row.data.profile || {};
  const profile = Object.entries(fieldLabels[locale]).map(([key,label]) => `<dt>${e(label)}</dt><dd style="white-space:pre-wrap;overflow-wrap:anywhere">${e(p[key])}</dd>`).join('');
  return `<article class="panel"><h2>${e(p.displayName)}</h2><p>${t.revision} ${e(row.revision)} · ${e(t[row.status] || row.status)} · ${e(row.submitted_at)}</p>${blocked ? `<p class="notice">${own ? t.self : t.excluded}</p>` : ''}<details><summary>${t.apply}</summary><dl>${profile}</dl></details>${feedbackHTML(row.review, locale)}<form data-applicant="${e(row.user_id)}"><label>${t.profile}${select('profile', row.review?.profile_decision || 'pending')}</label>${array(row.data.subjects).map((s,i) => `<section class="subject-card"><h3>${e(subjectLabel(s,locale))}</h3><p style="white-space:pre-wrap">${e(s.qualifications)}</p><p>${e(array(s.specialties).join(', '))}</p>${array(s.offerings).map(o => `<p>${e(o.title)} · ${e(o.durationMinutes)} ${sharedCopy[locale].minutes} · ${e(price(o,locale))} · ${e(o.lessonCount)} ${sharedCopy[locale].lessons} · ${e(sharedCopy[locale][o.deliveryMode] || o.deliveryMode)} · ${e(array(o.levels).join(', '))}</p>`).join('')}<label>${t.subject}${select(`subject-${i}`, row.review?.subject_decisions?.[i]?.decision || 'pending')}</label></section>`).join('')}<label>${t.feedback}<textarea name="feedback" maxlength="4000" ${own ? 'disabled' : ''}>${e(row.review?.feedback || '')}</textarea></label><p class="helper">${t.hint}</p><button type="submit" ${own ? 'disabled' : ''}>${t.save}</button><p role="status" class="status"></p></form></article>`;
}
